def = readtable('dataDEF.csv', "ReadVariableNames", false);
att = readtable('dataATT.csv', "ReadVariableNames", false);
mid = readtable('dataMID.csv', "ReadVariableNames", false);
gk = readtable('dataGK.csv', "ReadVariableNames", false);

predictorLabels = {'Age', 'Crossing', 'Finishing', 'HeadingAccuracy', 'ShortPassing', ...
    'Volleys', 'Dribbling', 'Curve', 'FKAccuracy', 'LongPassing', 'BallControl', ...
    'Acceleration', 'SprintSpeed', 'Agility', 'Reactions', 'Balance', 'ShotPower', ...
    'Jumping', 'Stamina', 'Strength', 'LongShots', 'Aggression', 'Interceptions', ...
    'Positioning', 'Vision', 'Penalties', 'Composure', 'Marking', 'StandingTackle', ...
    'SlidingTackle', 'GKDiving', 'GKHandling', 'GKKicking', 'GKPositioning', ...
    'GKReflexes', 'NRM_Height', 'NRM_Weight', 'Preferred Foot_Right', ...
    'International Reputation_2', 'International Reputation_3', ...
    'International Reputation_4', 'International Reputation_5', 'Weak Foot_2', ...
    'Weak Foot_3', 'Weak Foot_4', 'Weak Foot_5', 'Skill Moves_2', 'Skill Moves_3', ...
    'Skill Moves_4', 'Skill Moves_5', 'Asia', 'Cannot Find', 'Europe', 'North America', ...
    'Oceania', 'South America', 'Allsvenskan', 'Bundesliga', 'Bundesliga 2', 'CSL', ...
    'Calcio B', 'Camp. Scotiabank', 'Dominoâ€™s Ligue 2', 'EFL Championship', ...
    'EFL League One', 'EFL League Two', 'Ekstraklasa', 'Eliteserien', 'Eredivisie', ...
    'Hyundai A-League', 'K-League 1', 'LIGA Bancomer MX', 'LaLiga 1 I 2 I 3', ...
    'LaLiga Santander', 'Liga Dimayor', 'Liga NOS', 'Liga do Brasil', ...
    'Ligue 1 Conforama', 'MLS', 'Meiji Yasuda J1', 'Premier League', ...
    'Pro League', 'RSL', 'Rest of World', 'SAF', 'SSE Airtricity Lge', ...
    'Saudi Professional League', 'Scottish Prem', 'Serie A TIM', 'Super Lig', ...
    'Superliga', 'NRM_Position_ATT', 'NRM_Position_DEF', 'NRM_Position_GK', ...
    'NRM_Position_MID', '2019', '2020', '2021', '2022', '2023', '2024', '2025', '2026', ...
    'High-Low', 'High-Medium', 'Low-High', 'Low-Low', 'Low-Medium', 'Medium-High', ...
    'Medium-Low', 'Medium-Medium'}


X_Att = table2array(att(2:5208, 2 : 112));
Y_Att = table2array(att(2:5208, 113));

[b fitinfo] = lasso(X_Att, Y_Att, 'CV',10, 'Alpha', 1);
lassoPlot(b,fitinfo,'PlotType', 'Lambda', 'XScale', 'log', 'PredictorNames', predictorLabels);
title('Attackers Lasso Coefficents Plot');
lassoPlot(b,fitinfo,'PlotType','CV');	      % lassPlot with Cross Validation.
title('Attackers MSE Plot');

X_Mid = table2array(mid(2:7117, 2 : 112));
Y_Mid = table2array(mid(2:7117, 113));

[b fitinfo] = lasso(X_Mid, Y_Mid, 'CV',10, 'Alpha', 1);
lassoPlot(b,fitinfo,'PlotType', 'Lambda', 'XScale', 'log', 'PredictorNames', predictorLabels);
title('Midfielders Lasso Coefficents Plot');
lassoPlot(b,fitinfo,'PlotType','CV');
title('Midfielders MSE Plot');

X_Def = table2array(def(2:4511, 2 : 112));
Y_Def = table2array(def(2:4511, 113));

[b fitinfo] = lasso(X_Def, Y_Def, 'CV',10, 'Alpha', 1);
lassoPlot(b,fitinfo,'PlotType', 'Lambda', 'XScale', 'log', 'PredictorNames', predictorLabels);
title('Defenders Lasso Coefficents Plot')
lassoPlot(b,fitinfo,'PlotType','CV');	      % lassPlot with Cross Validation.
title('Defenders MSE Plot')

X_GK = table2array(gk(2:646, 2 : 112));
Y_GK = table2array(gk(2:646, 113));

[b fitinfo] = lasso(X_GK, Y_GK, 'CV',10, 'Alpha', 1);
lassoPlot(b,fitinfo,'PlotType', 'Lambda', 'XScale', 'log', 'PredictorNames', predictorLabels);
title('Goalkeepers Lasso Coefficents Plot')
lassoPlot(b,fitinfo,'PlotType','CV');
title('Goalkeepers MSE Plot')